In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('iris.csv')

In [4]:
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
df.columns =['sepal_length', 'sepal_width','petal_length','petal_width','flower_class']
df.loc[len(df.index)]=[5.1,3.5,1.4,0.2,'Iris-setosa'] #Since 1st row was replaced by column names.
new_df = pd.DataFrame(df)
new_df['flower_class'] = df.flower_class.astype('category')
new_df['flower_class']= new_df['flower_class'].cat.codes

In [6]:
new_df

sepal_length  sepal_width  petal_length  petal_width  flower_class
0             4.9          3.0           1.4          0.2             0
1             4.7          3.2           1.3          0.2             0
2             4.6          3.1           1.5          0.2             0
3             5.0          3.6           1.4          0.2             0
4             5.4          3.9           1.7          0.4             0
..            ...          ...           ...          ...           ...
145           6.3          2.5           5.0          1.9             2
146           6.5          3.0           5.2          2.0             2
147           6.2          3.4           5.4          2.3             2
148           5.9          3.0           5.1          1.8             2
149           5.1          3.5           1.4          0.2             0

[150 rows x 5 columns]

In [10]:
features = new_df.drop(columns=['flower_class']).values
target = new_df['flower_class'].values

In [11]:
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 0]


In [15]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(features,target, test_size=.2, )

In [16]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
pred = gnb.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score

acc  = accuracy_score(pred,y_test)
print(f"Accuracy : {acc*100}")

Accuracy : 90.0


In [23]:
from sklearn.metrics import precision_score, confusion_matrix,recall_score,f1_score

cm = confusion_matrix(y_test, pred)
precision = precision_score(y_test, pred,average='macro')
recall = recall_score(y_test, pred,average='macro')
f1 = f1_score(y_test,pred,average='macro')

In [24]:
print(cm)
print(precision)
print(recall)
print(f1)

[[ 9  0  0]
 [ 0 11  2]
 [ 0  1  7]]
0.898148148148148
0.907051282051282
0.9011764705882354


In [30]:
from sklearn.metrics import roc_curve

In [27]:
proba = gnb.predict_proba(x_test)

In [31]:
precision, recall, thresholds =roc_curve(y_test, proba)

ValueError: multiclass format is not supported